version: 0.2
env:
  variables:
    TEST: "abc"
phases:
  install:
    commands:
      - echo "Installing pre-requisites here"
  build:
    commands:
      - echo "Command 1"
      - echo "Command 2"
      - echo "Command 3"
      - echo "Command 4"
      - echo "Command 5"
  post_build:
    commands:
      - ls -l
